### PR TITLE
Added a New Schema File

### LINKED ISSUE #4: New Method to create schema files
**Describe the bug**
There is a better way to create schema files rather than manually going through each and every code.

**What's New**
The new method will be able to:
- Go through the models and automatically create schema.
- it will be less prone to human errors.
- we will always have the option to review each and every file we made.
- we will have separate file for every change we make in the models.
- the new files will automatically created into your local gamedoora-data, you will only require to review and push the changes.

**To Reproduce**
Make sure you have both gamedoora-model and gamedoora-data repository cloned into your local system and change the path of the new file created int the helper class in gamedoora-model.

**Expected behavior**
At Developer side: all you have to do is make the changes in the model class and push the changes into gamedoora-model and new files created within the gamedoora-data. 

**Future Scope**
A detailed, step-by-step read.me file will be added once this is issue is closed.

### PR DESCRIPTION
**Pull request by picksitquick**
Fixes #4 
Due to recent changes in the models, added a new schema file under the name beta-v2.sql
we can use the same to deploy in the environment.

There were several changes so I recommend please go through the file and let me know if any changes are needed.

Future Scope:
- Every time we make change in the models, our schema might need some change as well.
- Writing schema can be prone to human errors and negligence.
- In order to save time and increase efficiency I am creating a new issue under which will create a way for us to automatically generate schemas
- I already have a way to do so, a PR will be raised so that we can have those changes.

### CODE REVIEW

**Review by aprajshekhar — CHANGES_REQUESTED** [review]
This looks like a MySQL SQL file. This will not work with Postgres. Let's discuss during syncup.

**Comment by picksitquick** [comment]
Created a new schema file under the name gamedoora-beta-v3.sql, please check.
Also schema generator is ready in gamedoora-model and a PR has been raised.

**Review by aprajshekhar — COMMENTED** [review]
Thanks for the generated file. Just to confirm - have this been tried out on Postgresql's SQL console?

**Comment by picksitquick** [comment]
Hi @aprajshekhar ,
I tested the schema out on query tool in pgAdmin, and this is the result of it.
image

Please confirm, I think schema works cause all the tables with column names are being made, I tested it out in a test DB.

Changes:
- We do have a small problem in this file, the schema has been created twice, this error was caused because I ran this code twice without changing the name of the file so it made 2 copies within the same file. I will delete this and reupload a new file, 

- Also a small correction on line no.129: 
image

- Comments no longer work in columnDefinition for Postgresql, we have hibernate annotation @Comment which adds any additional comment needed

**Review by aprajshekhar — APPROVED** [review]
Thanks for verifying and pushing the new SQL script.

**Pull request merged**
